// packages/web-components/src/components/button/button.ts
import { css, html, LitElement, property } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map';
import { tokens } from './button.tokens';

export class Button extends LitElement {
	@property({ type: Boolean })
	disabled: boolean = false;

	@property({ type: Boolean })
	small: boolean = false;

	@property({ type: String })
	variant: 'primary' | 'secondary' | 'link' = 'primary';

	static get styles() {
		return css`
			button {
				min-width: ${tokens.buttonMinWidth};
				height: 40px;
				padding: 0 ${tokens.buttonHorizontalPadding};
				border-radius: ${tokens.buttonBorderRadius};
				cursor: pointer;
				font-size: 1rem;
				font-weight: bold;
				transition-duration: ${tokens.transitionDuration};
				transition-property: background-color, color;
			}

			button.small {
				min-width: ${tokens.buttonSmallMinWidth};
				height: 30px;
				font-size: 0.875rem;
			}

			button.primary {
				border: none;
				background-color: ${tokens.buttonPrimaryBgColor};
				color: ${tokens.buttonPrimaryTextColor};
			}

			button.primary:hover {
				background-color: ${tokens.buttonPrimaryHoverBgColor};
			}

			button.primary:active {
				background-color: ${tokens.buttonPrimaryActiveBgColor};
			}

			button.secondary {
				border: 1px solid ${tokens.buttonSecondaryBorderColor};
				background-color: ${tokens.buttonSecondaryBgColor};
				color: ${tokens.buttonSecondaryTextColor};
			}

			button.secondary:hover {
				background-color: ${tokens.buttonSecondaryHoverBgColor};
			}

			button.secondary:active {
				background-color: ${tokens.buttonSecondaryActiveBgColor};
			}

			button.link {
				min-width: initial;
				padding: 0;
				border: none;
				background: none;
				color: ${tokens.buttonLinkTextColor};
			}

			button.link:disabled,
			button.link:disabled:hover,
			button.link:disabled:active {
				background: none;
			}

			button.link:hover:not(:disabled) {
				text-decoration-line: underline;
				text-decoration-thickness: 2px;
			}

			button:focus-visible {
				outline-color: ${tokens.buttonPrimaryBgColor};
				outline-offset: 2px;
				outline-style: solid;
				outline-width: 2px;
			}

			button:disabled,
			button:disabled:hover,
			button:disabled:active {
				border: none;
				background-color: ${tokens.buttonDisabledBgColor};
				color: ${tokens.buttonDisabledTextColor};
				cursor: not-allowed;
			}

			@supports not selector(:focus-visible) {
				button:focus {
					outline-color: ${tokens.buttonPrimaryBgColor};
					outline-offset: 2px;
					outline-style: solid;
					outline-width: 2px;
				}
			}
		`;
	}

	getClass() {
		return classMap({
			small: this.small,
			primary: this.variant === 'primary',
			secondary: this.variant === 'secondary',
			link: this.variant === 'link',
		});
	}

	render() {
		return html`<button ?disabled=${this.disabled} class=${this.getClass()}>
			<slot></slot>
		</button>`;
	}
}

export function buttonRegister() {
	if (!window.customElements.get('skf-button')) {
		window.customElements.define('skf-button', Button);
	}
}

// src/components/button/Button.tsx
import { css } from '@emotion/react';
import styled from '@emotion/styled';
import React, { ReactChild } from 'react';
import { tokens } from './Button.Tokens';

/**
 * @category Props
 */
export interface ButtonProps {
	children: ReactChild;
	isDisabled?: boolean;
	onClick: () => void;
	small?: boolean;
	variant?: 'primary' | 'secondary' | 'link';
}

/**
 * @category Template
 */
const Button = ({ children, isDisabled, onClick, small, variant = 'primary' }: ButtonProps) => (
	<StButton disabled={isDisabled} small={small} onClick={onClick} variant={variant}>
		{children}
	</StButton>
);

export default Button;

/**
 * @category Styles
 */
type StProps = Partial<ButtonProps>;

const StButton = styled.button(
	({ small, variant }: StProps) => css`
		border-radius: ${tokens.buttonBorderRadius};
		cursor: pointer;
		font-size: 1rem;
		font-weight: bold;
		height: 40px;
		min-width: ${tokens.buttonMinWidth};
		padding: 0 ${tokens.buttonHorizontalPadding};
		transition-duration: ${tokens.transitionDuration};
		transition-property: background-color, color;

		&:focus-visible {
			outline-color: ${tokens.buttonPrimaryBgColor};
			outline-offset: 2px;
			outline-style: solid;
			outline-width: 2px;
		}

		@supports not selector(:focus-visible) {
			&:focus {
				outline-color: ${tokens.buttonPrimaryBgColor};
				outline-offset: 2px;
				outline-style: solid;
				outline-width: 2px;
			}
		}

		&:disabled,
		&:disabled:hover,
		&:disabled:active {
			background-color: ${tokens.buttonDisabledBgColor};
			border: none;
			color: ${tokens.buttonDisabledTextColor};
			cursor: not-allowed;
		}

		${small &&
		css`
			font-size: 0.875rem;
			height: 30px;
			min-width: ${tokens.buttonSmallMinWidth};
		`}

		${variant === 'primary' &&
		css`
			background-color: ${tokens.buttonPrimaryBgColor};
			border: none;
			color: ${tokens.buttonPrimaryTextColor};

			&:hover {
				background-color: ${tokens.buttonPrimaryHoverBgColor};
			}

			&:active {
				background-color: ${tokens.buttonPrimaryActiveBgColor};
			}
		`}

		${variant === 'secondary' &&
		css`
			background-color: ${tokens.buttonSecondaryBgColor};
			border: 1px solid ${tokens.buttonSecondaryBorderColor};
			color: ${tokens.buttonSecondaryTextColor};

			&:hover {
				background-color: ${tokens.buttonSecondaryHoverBgColor};
			}

			&:active {
				background-color: ${tokens.buttonSecondaryActiveBgColor};
			}
		`}

		${variant === 'link' &&
		css`
			background: none;
			border: none;
			color: ${tokens.buttonLinkTextColor};
			min-width: initial;
			padding: 0;

			&:disabled,
			&:disabled:hover,
			&:disabled:active {
				background: none;
			}

			&:hover:not(:disabled) {
				text-decoration-line: underline;
				text-decoration-thickness: 2px;
			}
		`}
	`
);
