// packages/react/src/atoms/text-input/TextInput.tsx
import styled from '@emotion/styled';
import React from 'react';
import { InputType } from '~types/input-type';

/**
 * @category Props
 */
type TextInputTypes = Extract<
	InputType,
	| 'date'
	| 'datetime-local'
	| 'datetime'
	| 'email'
	| 'hidden'
	| 'month'
	| 'number'
	| 'password'
	| 'search'
	| 'tel'
	| 'text'
	| 'time'
	| 'week'
>;

export interface TextInputProps {
	id: string;
	isDisabled?: boolean;
	isRequired?: boolean;
	type: TextInputTypes;
	value: string;
}

/**
 * @category Template
 */
const TextInput = ({ id, isDisabled, isRequired, type, value }: TextInputProps) => (
	<StTextInput disabled={isDisabled} id={id} required={isRequired} type={type} value={value} />
);

export default TextInput;

/**
 * @category Styles
 */
const StTextInput = styled.input`
	padding: 0.25rem;
	border: 1px solid #ccc;
	background: #fff;

	&:disabled {
		background: #ddd;
		cursor: not-allowed;
	}
`;

// packages/web-components/src/atoms/text-input/text-input.ts
import { css, html, LitElement, property } from 'lit-element';
import { InputType } from '~types/input-type.js';

type TextInputTypes = Extract<
	InputType,
	| 'date'
	| 'datetime-local'
	| 'datetime'
	| 'email'
	| 'hidden'
	| 'month'
	| 'number'
	| 'password'
	| 'search'
	| 'tel'
	| 'text'
	| 'time'
	| 'week'
>;

export class TextInput extends LitElement {
	@property({ type: String })
	class: string = '';

	@property({ type: Boolean })
	disabled: boolean = false;

	@property({ type: String })
	id: string = '';

	@property({ type: Boolean })
	required: boolean = false;

	@property({ type: String })
	type: TextInputTypes = 'text';

	@property({ type: String })
	value: string = '';

	static get styles() {
		return css`
			.text-input {
				padding: 0.25rem;
				border: 1px solid #ccc;
				background: #fff;
			}

			.text-input:disabled {
				background: #ddd;
				cursor: not-allowed;
			}
		`;
	}

	render() {
		return html`
			<input
				class="text-input ${this.class}"
				?disabled=${this.disabled}
				id=${this.id}
				?required=${this.required}
				type=${this.type}
				.value=${this.value}
			/>
		`;
	}
}

export function textInputRegister() {
	if (!window.customElements.get('skf-text-input')) {
		window.customElements.define('skf-text-input', TextInput);
	}
}
